SELECT 'EXPERT', SUPPLIER_ID,SUPPLIER_NUM,SUPPLIER_NAME,NVL(SUPPLIER_OUT_NETWORK,'Y'),
        SUPPLIER_MOBILE_PHONE,CRT_EMAIL AS EMAIL,DECODE(SUPPLIER_INACTD,NULL,'Y','N') AS ACTIVE,SUPPLIER_INACTD AS INACTIVATION_DATE
FROM CARS_SUPPLIER
WHERE SUPPLIER_INTERM ='E'
  AND NVL(SUPPLIER_OUT_NETWORK,'Y')='N'
UNION ALL 
SELECT 'GARAGE', SUPPLIER_ID,SUPPLIER_NUM,SUPPLIER_NAME,NVL(SUPPLIER_OUT_NETWORK,'Y') OUT_NETWORK,
       SUPPLIER_MOBILE_PHONE,CRT_EMAIL AS EMAIL,DECODE(SUPPLIER_INACTD,NULL,'Y','N') AS ACTIVE,SUPPLIER_INACTD AS INACTIVATION_DATE
FROM CARS_SUPPLIER
WHERE SUPPLIER_INTERM ='G'
  AND NVL(SUPPLIER_OUT_NETWORK,'Y')='N'

 