SELECT N.NOTIFICATION_ID,N.NOTIFICATION_VISA,N.NOTIFICATION_REPORTED_DATE,CP.POLICY_NUMBER,E.SUPPLIER_ID AS EXPERT_ID,E.SUPPLIER_NAME AS EXPERT_NAME,N.NOTIFICATION_CONTACT_NAME,N.NOTIFICATION_CONTACT_PHONE,
       T.LOSS_TOW_NBR_VEH_INVOLVED AS CARS_INVOLVED,       
       T.DISTRIBUTION_LOSS_TOWN_ID,O.TOWN_NAME||' '||O.TOWN_ARABIC_NAME AS TOWN_NAME,
       T.DISTRIBUTION_LOSS_ARRIVED,to_char(T.DISTRIBUTION_LOSS_ARRIVED_DATE,'dd/mm/yyyy hh:mi:ss') as DISTRIBUTION_LOSS_ARRIVED_DATE,
       C.CAR_OWNER_FIRST_NAME||' '||C.CAR_OWNER_FATHER_NAME||' '||C.CAR_OWNER_FAMILY_NAME AS CAR_OWNER,
       C.CAR_DRIVER_FIRST_NAME||' '||C.CAR_DRIVER_FATHER_NAME||' '||C.CAR_DRIVER_FAMILY_NAME AS CAR_DRIVER,
       (SELECT    MM.CAR_BRAND_DESCRIPTION
                  || ' '
                  || TR.CAR_TRADEMARK_DESCRIPTION
             FROM CARS_CAR_BRAND MM, CARS_CAR_TRADEMARK TR, CARS_CAR_SHAPE SC
            WHERE     MM.CAR_BRAND_ID = TR.CAR_BRAND_ID
                  AND TR.CAR_TRADEMARK_ID = SC.CAR_TRADEMARK_ID
                  AND SC.CAR_SHAPE_ID = C.CAR_SHAPE_ID)
             CAR_BRAND_TRADEMARK, C.CAR_PLATE_NUM,C.CAR_PLATE_CHAR
FROM CARS_NOTIFICATION N , CARS_LOSS_TOWING T,CARS_SUPPLIER E, CARS_LOSS_CAR C, CARS_TOWN O,
     CARS_POLICY_CAR CPC,CARS_POLICY CP
WHERE N.NOTIFICATION_ID=T.NOTIFICATION_ID
  AND T.LOSS_TOW_EXPERT_ID=E.SUPPLIER_ID
  AND T.LOSS_TOW_ID = C.CAR_CLAIM_ID
  AND C.CAR_SEQUENCE = 0
  AND O.TOWN_ID=T.DISTRIBUTION_LOSS_TOWN_ID
  AND CPC.CAR_ID=N.NOTIFICATION_POL_CAR_ID
  AND CPC.POLICY_ID=CP.POLICY_ID
  AND T.SYS_CREATED_DATE>= SYSDATE -1 


