namespace Api.Integrations.Push;

/// <summary>
/// One browser's web-push registration (design.md §4, added as realized in slice 3.4; §8's push rows
/// had no table because until now the only sender wrote to the console).
///
/// A user has as many rows as they have browsers — an expert with a phone and a desk machine gets the
/// popup on both, which is what §8's "push (popup) → Expert" means in practice.
///
/// **The keys are not secrets of ours.** <c>P256dh</c> and <c>Auth</c> are generated by the browser
/// and are what the push service requires in order for *that browser* to decrypt the payload; they
/// are useless without the endpoint, and the endpoint is useless without our VAPID private key. So
/// they are stored as the browser gave them, unlike §9's tokens, which are hashed precisely because
/// possession of them grants something.
/// </summary>
public sealed class PushSubscription
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    /// <summary>The push service's URL for this browser. Long, and vendor-shaped.</summary>
    public required string Endpoint { get; set; }

    /// <summary>
    /// SHA-256 of <see cref="Endpoint"/>, and the reason this column exists at all: the unique index
    /// that makes re-subscribing an upsert cannot sit on the endpoint itself, because SQL Server caps
    /// an index key at 900 bytes and a push endpoint can exceed it. Hashing is for *length*, not for
    /// secrecy — hence the endpoint is stored beside it in the clear.
    /// </summary>
    public required string EndpointHash { get; set; }

    /// <summary>The browser's public key for payload encryption (base64url, as it was given).</summary>
    public required string P256dh { get; set; }

    /// <summary>The browser's auth secret for payload encryption (base64url, as it was given).</summary>
    public required string Auth { get; set; }

    public DateTime CreatedAt { get; set; }

    /// <summary>When a push was last accepted for this browser. Support's "is this device still live".</summary>
    public DateTime? LastUsedAt { get; set; }

    /// <summary>
    /// Set when the push service answered 404 or 410 — the browser is gone and this endpoint will
    /// never work again.
    ///
    /// Revoked rather than deleted **for this case specifically**, because it is something that
    /// happened *to* the user: "this expert stopped getting popups on the 14th, and here is why"
    /// stays answerable, and the `notification` rows naming this subscription still resolve.
    ///
    /// An explicit unsubscribe is different and does delete the row (see the DELETE endpoint): the
    /// user asked to stop, and re-enabling later should look like a fresh registration rather than a
    /// resurrection. The cost is recorded rather than hidden — historical `notification` rows for a
    /// deleted device point at an id that is no longer there.
    /// </summary>
    public DateTime? RevokedAt { get; set; }
}

/// <summary>
/// Column widths, in one place because two things must agree about them: the EF configuration that
/// creates the columns, and the endpoint that refuses oversized input before it reaches them. Split
/// across two files, a widened column and a stale check turn "your browser sent a long endpoint" into
/// a 500 at the database.
/// </summary>
public static class PushSubscriptionLimits
{
    /// <summary>Comfortably past every push service's endpoint, and short enough to stay a plain nvarchar.</summary>
    public const int EndpointLength = 2048;

    /// <summary>A base64url P-256 point is 87 characters; the slack absorbs padding and vendor drift.</summary>
    public const int P256dhLength = 200;

    /// <summary>The auth secret is 16 bytes — 22 base64url characters.</summary>
    public const int AuthLength = 50;
}
