// <auto-generated />
using System;
using Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260825164512_AddOutboxLastAttemptAt")]
    partial class AddOutboxLastAttemptAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Integrations.Push.PushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("auth");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("endpoint");

                    b.Property<string>("EndpointHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("endpoint_hash");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_used_at");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("p256dh");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasFilter("[revoked_at] IS NULL");

                    b.HasIndex("UserId", "EndpointHash")
                        .IsUnique();

                    b.ToTable("push_subscription", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime2")
                        .HasColumnName("at");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detail");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityKind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("entity_kind");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("EntityKind", "EntityId");

                    b.ToTable("audit_log", null, t =>
                        {
                            t.HasTrigger("TR_audit_log_append_only");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Api.Modules.Broker.BrokerRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("BrokerDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("broker_display_name");

                    b.Property<Guid>("BrokerUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("broker_user_id");

                    b.Property<decimal?>("CarValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("car_value");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerMobile")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("customer_mobile");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<string>("EmailRecipient")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("email_recipient");

                    b.Property<DateTime?>("EmailedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("emailed_at");

                    b.Property<decimal?>("EstimatedPremium")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("estimated_premium");

                    b.Property<string>("InsuranceType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("insurance_type");

                    b.Property<string>("InsuredAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("insured_address");

                    b.Property<string>("InsuredName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("insured_name");

                    b.Property<int>("Option")
                        .HasColumnType("int")
                        .HasColumnName("option");

                    b.Property<string>("State")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("state");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id");

                    b.HasIndex("BrokerUserId", "CreatedAt");

                    b.ToTable("broker_request", null, t =>
                        {
                            t.HasCheckConstraint("CK_broker_request_option", "[option] IN (1, 2)");

                            t.HasCheckConstraint("CK_broker_request_state", "[state] IN ('draft', 'submitted', 'link_issued', 'customer_in_progress', 'ready_to_send', 'sent', 'expired')");
                        });
                });

            modelBuilder.Entity("Api.Modules.Claims.CachedClaim", b =>
                {
                    b.Property<string>("VisaNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("visa_no");

                    b.Property<DateOnly>("AccidentDate")
                        .HasColumnType("date")
                        .HasColumnName("accident_date");

                    b.Property<string>("CarMakeModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("car_make_model");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("fetched_at");

                    b.Property<string>("InsuredName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("insured_name");

                    b.Property<string>("InsuredPhone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("insured_phone");

                    b.Property<string>("PlateNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("plate_no");

                    b.Property<string>("PolicyNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("policy_no");

                    b.HasKey("VisaNo");

                    b.ToTable("claim", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Declarations.Declaration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("decided_at");

                    b.Property<Guid>("GarageUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("garage_user_id");

                    b.Property<string>("InsuredName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("insured_name");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("note");

                    b.Property<Guid?>("OfficerUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("officer_user_id");

                    b.Property<string>("PlateNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("plate_no");

                    b.Property<DateTime?>("RepairDocsSubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("repair_docs_submitted_at");

                    b.Property<DateTime?>("RepairsStartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("repairs_started_at");

                    b.Property<string>("State")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)")
                        .HasColumnName("state");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at");

                    b.Property<string>("VisaNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("visa_no");

                    b.HasKey("Id");

                    b.HasIndex("OfficerUserId");

                    b.HasIndex("GarageUserId", "CreatedAt");

                    b.HasIndex("State", "SubmittedAt");

                    b.ToTable("declaration", null, t =>
                        {
                            t.HasCheckConstraint("CK_declaration_decision", "(CASE WHEN [state] IN ('approved', 'rejected', 'repair_docs_submitted', 'repairs_in_progress') THEN 1 ELSE 0 END) = (CASE WHEN [officer_user_id] IS NOT NULL THEN 1 ELSE 0 END) AND (CASE WHEN [state] IN ('approved', 'rejected', 'repair_docs_submitted', 'repairs_in_progress') THEN 1 ELSE 0 END) = (CASE WHEN [decided_at] IS NOT NULL THEN 1 ELSE 0 END) AND (CASE WHEN [state] IN ('approved', 'repair_docs_submitted', 'repairs_in_progress') THEN 1 ELSE 0 END) = (CASE WHEN [visa_no] IS NOT NULL THEN 1 ELSE 0 END)");

                            t.HasCheckConstraint("CK_declaration_state", "[state] IN ('approved', 'draft', 'rejected', 'repair_docs_submitted', 'repairs_in_progress', 'submitted')");
                        });
                });

            modelBuilder.Entity("Api.Modules.Declarations.DeclarationComment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeclarationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("declaration_id");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("DeclarationId", "CreatedAt");

                    b.ToTable("declaration_comment", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Expert.ExpertAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<double?>("ArrivalLat")
                        .HasColumnType("float")
                        .HasColumnName("arrival_lat");

                    b.Property<double?>("ArrivalLng")
                        .HasColumnType("float")
                        .HasColumnName("arrival_lng");

                    b.Property<DateTime?>("ArrivedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("arrived_at");

                    b.Property<Guid>("ExpertUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("expert_user_id");

                    b.Property<string>("Next3AssignmentRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("next3_assignment_ref");

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("notified_at");

                    b.Property<DateTime?>("OpenedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("opened_at");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("received_at");

                    b.Property<string>("VisaNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("visa_no");

                    b.HasKey("Id");

                    b.HasIndex("Next3AssignmentRef")
                        .IsUnique();

                    b.HasIndex("ExpertUserId", "ReceivedAt");

                    b.ToTable("expert_assignment", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Media.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("BlobDeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("blob_deleted_at");

                    b.Property<string>("BlobKey")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("blob_key");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("bucket");

                    b.Property<string>("ClarityResult")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("clarity_result");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<string>("DocType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("doc_type");

                    b.Property<string>("FileName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("file_name");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("origin");

                    b.Property<Guid?>("OutboxMessageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("outbox_message_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("owner_kind");

                    b.Property<string>("PushStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("push_status");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.HasKey("Id");

                    b.HasIndex("BlobKey")
                        .HasFilter("[blob_deleted_at] IS NULL");

                    b.HasIndex("OutboxMessageId")
                        .IsUnique()
                        .HasFilter("[outbox_message_id] IS NOT NULL");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("OutboxMessageId"), new[] { "CreatedAt", "BlobKey" });

                    b.HasIndex("OwnerKind", "OwnerId");

                    b.HasIndex("OwnerKind", "OwnerId", "Bucket")
                        .IsUnique()
                        .HasFilter("[bucket] IN ('public_car_front', 'public_car_left', 'public_car_rear', 'public_car_right', 'public_car_roof')");

                    b.ToTable("document", null, t =>
                        {
                            t.HasCheckConstraint("CK_document_bucket", "[bucket] IN ('approval_image', 'broker_document', 'damage_diagram', 'discharge', 'expert_report', 'garage_car_photo', 'garage_documents', 'insured_car_photo', 'insured_documents', 'invoice', 'public_car_front', 'public_car_left', 'public_car_rear', 'public_car_right', 'public_car_roof', 'public_document', 'repair_photo', 'tp_car_photo', 'tp_documents', 'voice_note')");

                            t.HasCheckConstraint("CK_document_clarity_result", "[clarity_result] IN ('passed', 'not_applicable')");

                            t.HasCheckConstraint("CK_document_origin", "[origin] IN ('captured', 'uploaded')");

                            t.HasCheckConstraint("CK_document_owner_kind", "[owner_kind] IN ('assignment', 'declaration', 'broker_request')");

                            t.HasCheckConstraint("CK_document_push_status", "[push_status] IN ('deferred', 'n/a', 'queued')");

                            t.HasCheckConstraint("CK_document_push_status_outbox", "([push_status] = 'queued' AND [outbox_message_id] IS NOT NULL) OR ([push_status] IN ('deferred', 'n/a') AND [outbox_message_id] IS NULL)");
                        });
                });

            modelBuilder.Entity("Api.Modules.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error");

                    b.Property<string>("Payload")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload");

                    b.Property<string>("RecipientAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("recipient_address");

                    b.Property<Guid?>("RecipientUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("recipient_user_id");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("status");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("template");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("RecipientUserId", "CreatedAt");

                    b.ToTable("notification", null, t =>
                        {
                            t.HasCheckConstraint("CK_notification_channel", "[channel] IN ('push', 'sms', 'email')");

                            t.HasCheckConstraint("CK_notification_status", "[status] IN ('queued', 'sent', 'failed')");
                        });
                });

            modelBuilder.Entity("Api.Modules.PublicSurface.PublicLinkToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("BrokerRequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("broker_request_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("locked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("token_hash");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.HasKey("Id");

                    b.HasIndex("BrokerRequestId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("public_link_token", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Users.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("display_name");

                    b.Property<DateTime?>("InactivatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("inactivated_at");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("app_user", null, t =>
                        {
                            t.HasCheckConstraint("CK_app_user_role", "[role] IN ('expert', 'garage', 'claim_officer', 'broker', 'admin')");

                            t.HasCheckConstraint("CK_app_user_status", "[status] IN ('invited', 'active', 'inactive')");
                        });
                });

            modelBuilder.Entity("Api.Modules.Users.BrokerProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<string>("IrisCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("iris_code");

                    b.HasKey("UserId");

                    b.ToTable("broker_profile", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Users.ClaimOfficerProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<string>("Next3User")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("next3_user");

                    b.HasKey("UserId");

                    b.ToTable("claim_officer_profile", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Users.ExpertProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("InactivatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("inactivated_at");

                    b.Property<string>("Next3Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("next3_id");

                    b.HasKey("UserId");

                    b.HasIndex("Next3Id")
                        .IsUnique()
                        .HasFilter("[next3_id] IS NOT NULL");

                    b.ToTable("expert_profile", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Users.GarageProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("address");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("contact_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("InactivatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("inactivated_at");

                    b.Property<string>("Mobile")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("mobile");

                    b.Property<string>("Next3Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("next3_id");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("opening_hours");

                    b.Property<string>("Phone")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("phone");

                    b.HasKey("UserId");

                    b.HasIndex("Next3Id")
                        .IsUnique()
                        .HasFilter("[next3_id] IS NOT NULL");

                    b.ToTable("garage_profile", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Users.Invite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("invite", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Users.OtpChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("int")
                        .HasColumnName("attempts");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.HasIndex("Phone");

                    b.ToTable("otp_challenge", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("Api.Outbox.Next3OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("attempts");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_error");

                    b.Property<DateTime>("NextRetryAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("next_retry_at");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("operation");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("VisaNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("visa_no");

                    b.HasKey("Id");

                    b.HasIndex("VisaNo");

                    b.HasIndex("Status", "NextRetryAt");

                    b.ToTable("next3_outbox", null, t =>
                        {
                            t.HasCheckConstraint("CK_next3_outbox_operation", "[operation] IN ('upload_document', 'update_arrival', 'push_approval')");

                            t.HasCheckConstraint("CK_next3_outbox_status", "[status] IN ('pending', 'processing', 'sent', 'failed')");
                        });
                });

            modelBuilder.Entity("Api.Integrations.Push.PushSubscription", b =>
                {
                    b.HasOne("Api.Modules.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Modules.Audit.AuditLog", b =>
                {
                    b.HasOne("Api.Modules.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId");
                });

            modelBuilder.Entity("Api.Modules.Broker.BrokerRequest", b =>
                {
                    b.HasOne("Api.Modules.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("BrokerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Modules.Declarations.Declaration", b =>
                {
                    b.HasOne("Api.Modules.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("GarageUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Modules.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("OfficerUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Api.Modules.Declarations.DeclarationComment", b =>
                {
                    b.HasOne("Api.Modules.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Modules.Declarations.Declaration", null)
                        .WithMany()
                        .HasForeignKey("DeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Modules.Expert.ExpertAssignment", b =>
                {
                    b.HasOne("Api.Modules.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ExpertUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Modules.Notifications.Notification", b =>
                {
                    b.HasOne("Api.Modules.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("RecipientUserId");
                });

            modelBuilder.Entity("Api.Modules.PublicSurface.PublicLinkToken", b =>
                {
                    b.HasOne("Api.Modules.Broker.BrokerRequest", null)
                        .WithMany()
                        .HasForeignKey("BrokerRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Modules.Users.BrokerProfile", b =>
                {
                    b.HasOne("Api.Modules.Users.AppUser", null)
                        .WithOne()
                        .HasForeignKey("Api.Modules.Users.BrokerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Modules.Users.ClaimOfficerProfile", b =>
                {
                    b.HasOne("Api.Modules.Users.AppUser", null)
                        .WithOne()
                        .HasForeignKey("Api.Modules.Users.ClaimOfficerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Modules.Users.ExpertProfile", b =>
                {
                    b.HasOne("Api.Modules.Users.AppUser", null)
                        .WithOne()
                        .HasForeignKey("Api.Modules.Users.ExpertProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Modules.Users.GarageProfile", b =>
                {
                    b.HasOne("Api.Modules.Users.AppUser", null)
                        .WithOne()
                        .HasForeignKey("Api.Modules.Users.GarageProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Modules.Users.Invite", b =>
                {
                    b.HasOne("Api.Modules.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Modules.Users.RefreshToken", b =>
                {
                    b.HasOne("Api.Modules.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
